name: Release Crate

on:
  push:
    tags:
      - 'v*' # Tự chạy khi có tag dạng v0.1.*

permissions:
  contents: write
jobs:
  publish-crate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # để đảm bảo lấy đầy đủ commit và tag

      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Verify tag matches Cargo.toml version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          CARGO_VERSION=$(grep '^version' Cargo.toml | head -n1 | cut -d '"' -f2)
          if [ "$TAG_VERSION" != "$CARGO_VERSION" ]; then
            echo "❌ Tag version ($TAG_VERSION) không khớp với Cargo.toml ($CARGO_VERSION)"
            exit 1
          fi

      - name: Verify dependencies
        run: |
          if ! grep -q 'serde' Cargo.toml || ! grep -q 'chrono' Cargo.toml; then
            echo "❌ Missing required dependencies (serde or chrono)"
            exit 1
          fi

      - name: Dry run publish
        run: cargo publish --dry-run

      - name: Build crate package
        run: cargo package

      - name: Update crates-index (manual)
        env:
          CRATE_INDEX_TOKEN: ${{ secrets.CRATE_INDEX_TOKEN }}
        run: |
          set -euo pipefail

          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          CRATE_NAME=$(grep '^name' Cargo.toml | head -n1 | cut -d '"' -f2)
          CRATE_URL="https://github.com/${{ github.repository }}/releases/download/v$TAG_VERSION/${CRATE_NAME}-$TAG_VERSION.crate"

          echo "Updating index for $CRATE_NAME v$TAG_VERSION -> $CRATE_URL"

          # Clone index (use token with push rights)
          git clone https://x-access-token:${CRATE_INDEX_TOKEN}@github.com/alexsong3/crates-index.git
          cd crates-index

          # Ensure remote origin contains token for authenticated push
          git remote set-url origin "https://x-access-token:${CRATE_INDEX_TOKEN}@github.com/alexsong3/crates-index.git"

          # compute index path using crates.io-style layout
          name="$CRATE_NAME"
          len=${#name}
          if [ "$len" -eq 1 ]; then
            idx_path="1/$name"
          elif [ "$len" -eq 2 ]; then
            idx_path="2/$name"
          elif [ "$len" -eq 3 ]; then
            prefix=${name:0:1}
            idx_path="3/$prefix/$name"
          else
            a=${name:0:2}
            b=${name:2:4}
            idx_path="$a/$b/$name"
          fi

          mkdir -p "$(dirname "$idx_path")"

          # compute checksum of the .crate
          CKSUM=$(sha256sum ../target/package/${CRATE_NAME}-${TAG_VERSION}.crate | awk '{print $1}')
          echo "checksum: $CKSUM"

          # generate JSON entry
          python3 - <<PY > /tmp/crate_entry.json
            import json
            entry = {
              "name": "$CRATE_NAME",
              "vers": "$TAG_VERSION",
              "deps": [],
              "cksum": "$CKSUM",
              "features": {},
              "yanked": False
            }
            print(json.dumps(entry, separators=(',',':')))
            PY

          # append the entry as one line (create file if missing)
          printf "%s\n" "$(cat /tmp/crate_entry.json)" >> "$idx_path"

          git add "$idx_path"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # commit & push using origin which contains token
          git commit -m "Update $CRATE_NAME to v$TAG_VERSION"
          git push origin main
        shell: bash